# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 14:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import fernet_fields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admin',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('uname', fernet_fields.fields.EncryptedTextField()),
                ('upass', fernet_fields.fields.EncryptedTextField()),
            ],
        ),
        migrations.CreateModel(
            name='attendence',
            fields=[
                ('aid', models.AutoField(primary_key=True, serialize=False)),
                ('adate', models.DateField()),
                ('atime', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='classes',
            fields=[
                ('clid', models.AutoField(primary_key=True, serialize=False)),
                ('clname', fernet_fields.fields.EncryptedTextField()),
            ],
        ),
        migrations.CreateModel(
            name='course',
            fields=[
                ('coid', models.AutoField(primary_key=True, serialize=False)),
                ('coname', fernet_fields.fields.EncryptedTextField()),
                ('copattern', fernet_fields.fields.EncryptedIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='division',
            fields=[
                ('did', models.AutoField(primary_key=True, serialize=False)),
                ('dname', fernet_fields.fields.EncryptedTextField()),
                ('dcapacity', fernet_fields.fields.EncryptedIntegerField()),
                ('classes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sample.classes')),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('adminssion_no', models.IntegerField(primary_key=True, serialize=False)),
                ('roll', fernet_fields.fields.EncryptedIntegerField()),
                ('sname', fernet_fields.fields.EncryptedTextField()),
                ('smobile', fernet_fields.fields.EncryptedIntegerField()),
                ('semail', fernet_fields.fields.EncryptedTextField()),
                ('spassword', fernet_fields.fields.EncryptedTextField()),
            ],
        ),
        migrations.CreateModel(
            name='subject',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('scode', fernet_fields.fields.EncryptedIntegerField()),
                ('sname', fernet_fields.fields.EncryptedTextField()),
                ('max_lacture', fernet_fields.fields.EncryptedIntegerField(null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sample.course')),
            ],
        ),
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('tid', models.IntegerField(default='', primary_key=True, serialize=False)),
                ('tname', fernet_fields.fields.EncryptedTextField()),
                ('designation', fernet_fields.fields.EncryptedTextField()),
                ('contact_mob', fernet_fields.fields.EncryptedIntegerField()),
                ('email', fernet_fields.fields.EncryptedEmailField(max_length=254)),
                ('tpassword', fernet_fields.fields.EncryptedTextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='timetable',
            fields=[
                ('tmid', models.AutoField(primary_key=True, serialize=False)),
                ('slot_no', fernet_fields.fields.EncryptedIntegerField()),
                ('slot_day', fernet_fields.fields.EncryptedIntegerField()),
                ('slot_s_time', models.TimeField()),
                ('slot_e_time', models.TimeField()),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sample.division')),
            ],
        ),
        migrations.AddField(
            model_name='subject',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sample.teacher'),
        ),
        migrations.AddField(
            model_name='classes',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sample.course'),
        ),
        migrations.AddField(
            model_name='attendence',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sample.division'),
        ),
        migrations.AddField(
            model_name='attendence',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sample.student'),
        ),
        migrations.AddField(
            model_name='attendence',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sample.subject'),
        ),
    ]
