# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tname', models.CharField(max_length=40)),
                ('designation', models.CharField(max_length=20)),
                ('contact_res', models.IntegerField(max_length=15)),
                ('contact_mob', models.IntegerField(max_length=12)),
                ('email', models.CharField(max_length=30)),
            ],
        ),
    ]
