# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 23:49
from __future__ import unicode_literals

from django.db import migrations
import fernet_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='roll',
            field=fernet_fields.fields.EncryptedIntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='student',
            name='spassword',
            field=fernet_fields.fields.EncryptedTextField(default=''),
        ),
    ]
