# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='contact_mob',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='contact_res',
            field=models.IntegerField(),
        ),
    ]
