# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 11:59
from __future__ import unicode_literals

from django.db import migrations
import fernet_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0003_auto_20170903_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='tname',
            field=fernet_fields.fields.EncryptedTextField(),
        ),
    ]
