# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 12:30
from __future__ import unicode_literals

from django.db import migrations
import fernet_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0005_auto_20170903_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='contact_mob',
            field=fernet_fields.fields.EncryptedIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='contact_res',
            field=fernet_fields.fields.EncryptedIntegerField(default=1),
            preserve_default=False,
        ),
    ]
