# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-21 03:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import fernet_fields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admin',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('uname', models.TextField()),
                ('upass', fernet_fields.fields.EncryptedTextField()),
                ('lastlogin', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='attendence',
            fields=[
                ('aid', models.AutoField(primary_key=True, serialize=False)),
                ('adate', models.DateField()),
                ('atime', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='classes',
            fields=[
                ('clid', models.AutoField(primary_key=True, serialize=False)),
                ('clname', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='course',
            fields=[
                ('coid', models.AutoField(primary_key=True, serialize=False)),
                ('coname', models.TextField()),
                ('copattern', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='division',
            fields=[
                ('did', models.AutoField(primary_key=True, serialize=False)),
                ('dname', models.TextField()),
                ('dcapacity', models.IntegerField()),
                ('classes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendence.classes')),
            ],
        ),
        migrations.CreateModel(
            name='divtimetable',
            fields=[
                ('dtmid', models.AutoField(primary_key=True, serialize=False)),
                ('slot_no', fernet_fields.fields.EncryptedIntegerField()),
                ('slot_day', fernet_fields.fields.EncryptedIntegerField()),
                ('slot_s_time', models.TimeField()),
                ('slot_e_time', models.TimeField()),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendence.division')),
            ],
        ),
        migrations.CreateModel(
            name='lab',
            fields=[
                ('slid', models.AutoField(primary_key=True, serialize=False)),
                ('slname', fernet_fields.fields.EncryptedTextField()),
                ('slstart', fernet_fields.fields.EncryptedIntegerField()),
                ('slend', fernet_fields.fields.EncryptedIntegerField()),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendence.division')),
            ],
        ),
        migrations.CreateModel(
            name='labtimetable',
            fields=[
                ('ltmid', models.AutoField(primary_key=True, serialize=False)),
                ('slot_day', fernet_fields.fields.EncryptedIntegerField()),
                ('slot_s_time', models.TimeField()),
                ('slot_e_time', models.TimeField()),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendence.lab')),
            ],
        ),
        migrations.CreateModel(
            name='lattendence',
            fields=[
                ('laid', models.AutoField(primary_key=True, serialize=False)),
                ('adate', models.DateField()),
                ('atime', models.TimeField()),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendence.lab')),
            ],
        ),
        migrations.CreateModel(
            name='mail',
            fields=[
                ('mid', models.AutoField(primary_key=True, serialize=False)),
                ('sender', fernet_fields.fields.EncryptedTextField()),
                ('to', fernet_fields.fields.EncryptedTextField()),
                ('subject', fernet_fields.fields.EncryptedTextField(default='')),
                ('message', fernet_fields.fields.EncryptedTextField()),
                ('mdate', models.DateField()),
                ('mtime', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('roll', fernet_fields.fields.EncryptedIntegerField(default='')),
                ('sname', fernet_fields.fields.EncryptedTextField()),
                ('smobile', fernet_fields.fields.EncryptedIntegerField(default='')),
                ('semail', fernet_fields.fields.EncryptedTextField(default='')),
                ('spassword', fernet_fields.fields.EncryptedTextField(default='')),
                ('lastlogin', models.DateTimeField(blank=True, null=True)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendence.division')),
            ],
        ),
        migrations.CreateModel(
            name='subject',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('scode', fernet_fields.fields.EncryptedTextField()),
                ('sname', fernet_fields.fields.EncryptedTextField()),
                ('max_lacture', fernet_fields.fields.EncryptedIntegerField(default='')),
                ('classes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendence.classes')),
            ],
        ),
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('tid', models.IntegerField(primary_key=True, serialize=False)),
                ('tname', fernet_fields.fields.EncryptedTextField()),
                ('designation', fernet_fields.fields.EncryptedTextField()),
                ('contact_mob', fernet_fields.fields.EncryptedIntegerField(default='')),
                ('email', fernet_fields.fields.EncryptedEmailField(default='', max_length=254)),
                ('tpassword', fernet_fields.fields.EncryptedTextField(default='')),
                ('lastlogin', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='subject',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendence.teacher'),
        ),
        migrations.AddField(
            model_name='lattendence',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendence.student'),
        ),
        migrations.AddField(
            model_name='divtimetable',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendence.subject'),
        ),
        migrations.AddField(
            model_name='classes',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendence.course'),
        ),
        migrations.AddField(
            model_name='attendence',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendence.division'),
        ),
        migrations.AddField(
            model_name='attendence',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendence.student'),
        ),
        migrations.AddField(
            model_name='attendence',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendence.subject'),
        ),
    ]
